### ISSUE TITLE
error on starting node

### ISSUE THREAD

**Issue by am06** [stephenfewer/grinder#52]
Hi Stephen,

I get this error on starting a node with ruby 2.1.5

[+G+] Starting at 2015-02-15 12:56:48

C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': 1114: A dynamic link library (DLL) initialization routine failed.   - C:/github/grinder/node/lib/metasm/metasm/dynldr-windows-x64-19.so (LoadError)
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/github/grinder/node/lib/metasm/metasm/dynldr.rb:612:in `start'
        from C:/github/grinder/node/lib/metasm/metasm/dynldr.rb:1297:in `<class:DynLdr>'
        from C:/github/grinder/node/lib/metasm/metasm/dynldr.rb:11:in `<module:Metasm>'
        from C:/github/grinder/node/lib/metasm/metasm/dynldr.rb:10:in `<top (required)>'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/github/grinder/node/lib/metasm/metasm/os/windows.rb:8:in `<top (required)>'
        from C:/github/grinder/node/core/configuration.rb:36:in `config_init'
        from grinder.rb:142:in `run'
        from grinder.rb:258:in `<main>'

C:\github\grinder\node>

Before this I've tried another ruby version and that also failed. What exact version of ruby are you guys using?

Cheers,

**Comment by mutfuzz** [comment]
i am using rubyinstaller-2.0.0-p598-x64.exe on windows 8.1 x64

**Comment by am06** [comment]
so am I . that was a config issue on my side, I fixed that now I get this:

"+G+] Starting at 2015-02-15 16:33:48
+G+] Using the config file 'config'...
+G+] Bringing up Grinder node 'G1' with ruby 2.0.0 (64-bit)...
+G+] Started the Grinder continue process 9472
+S+] Starting at 2015-02-15 16:33:48
:/Ruby200-x64/lib/ruby/2.0.0/uri/generic.rb:214:in `initialize': the scheme http does not accept registry part: :80 (or bad hostname?) (URI::InvalidURIError)
       from C:/Ruby200-x64/lib/ruby/2.0.0/uri/http.rb:84:in `initialize'
       from C:/Ruby200-x64/lib/ruby/2.0.0/uri/common.rb:214:in `new'
       from C:/Ruby200-x64/lib/ruby/2.0.0/uri/common.rb:214:in `parse'
       from C:/Ruby200-x64/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
       from C:/Ruby200-x64/lib/ruby/2.0.0/uri/common.rb:996:in `URI'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1027:in `proxy_uri'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1014:in `proxy?'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:868:in `connect'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in `start'
       from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1367:in `request'
       from C:/github/grinder/node/core/webstats.rb:125:in `_send_request2'
       from C:/github/grinder/node/core/webstats.rb:93:in `_send_request1'
       from C:/github/grinder/node/core/webstats.rb:47:in `update_job_status'
       from ./core/server.rb:211:in `initialize'
       from ./core/server.rb:350:in `new'
       from ./core/server.rb:350:in `<main>'
+G+] Started the Grinder server process 1528"


seems like Ruby is crappy to me.

**Comment by am06** [comment]
this is unbelievable, this ruby.....I'm trying to hack those lines where it errors and I can't convince it to make a simple http request....tried lots of samples from google.

**Comment by am06** [comment]
solved it. another config issue in setting:

$webstats_baseurl         = 'localhost/fuzzer/status.php'

And the error message was very useless as you can see......Now it's running but nothing is logged in my databases, I don't see any nodes running under my fuzzers section. Will continue hacking.

**Comment by sam-b** [comment]
@am06 what was your config issue? I'm getting the same error and can't work it.

**Comment by am06** [comment]
the $webstats_baseurl = 'localhost/fuzzer/status.php'. as written above.
