### ISSUE TITLE
continue.exe not a valid win32 application on XP

### ISSUE THREAD

**Issue by fengZeLoo** [stephenfewer/grinder#55]
The file, continue.exe, did not work in my environment.
error msg:
[+G+] Bringing up Grinder node 'G1' with ruby 1.9.3 (32-bit)...
grinder.rb:161:in 'spaen': Exec format error - .\data\continue.exe(Errno::ENOEXEC)
    from grinder.rb:161:in 'run'
    from grinder.rb:258:in '(main)'

I install the ruby 1.9 and done all install for grinder node.

**Comment by am06** [comment]
same problem here. Anybody got this working on windows XP? First of all is it because of ruby or continue.exe ?

**Comment by stephenfewer** [comment]
Just check on XP and continue.exe is not a valid application on that platform. Probably need to be built with an older version of MSVC, which I am not going to do.

@am06 continue.exe runs a loop that looks for common dialogs and hits the close button so the fuzzer can keep running. See the source here:
https://github.com/stephenfewer/grinder/blob/master/node/source/continue/main.c
