### ISSUE TITLE
Firefox not logging

### ISSUE THREAD

**Issue by pyoor** [stephenfewer/grinder#60]
I know that has been discussed a bit in other issues but I thought it deserved it's own thread.  There's an issue right now logging crash data for Firefox 38.0.5 and 39.0.  Grinder reports no errors attaching to the process but no log file is created:

[+G+] Starting at 2015-07-05 19:03:23
[+G+] Using the config file 'config'...
[+G+] Bringing up Grinder node 'Test-1' with ruby 1.9.3 (32-bit)...
[+G+] Started the Grinder continue process 5016
[+S+] Starting at 2015-07-05 19:03:25
[+S+] Adding fuzzer 'Fuzzer_15-07-05_18-42-18' to the testcase server
[+S+] Testcase server running on 127.0.0.1:8080
[+G+] Started the Grinder server process 6052
[+G+] Started the Grinder debugger process 5148
[+D+] Starting at 2015-07-05 19:03:29
[-D-] Found an instance of firefox.exe already running, killing...
[-D-] Received an interrupt in main debugger loop.
./browser/firefox.rb: Interrupt
[+G+] Started the Grinder debugger process 5876
[+D+] Starting at 2015-07-05 19:04:14
[+D+] Using the symbol path 'SRV*C:\symbols\*http://msdl.microsoft.com/download/symbols;SRV*C:\symbols\*http://symbols.mozilla.org/firefox'.
[+D+] Running 'C:\Program Files\Mozilla Firefox\firefox.exe'
[+D+] Attached debugger to new 32-bit process 4932.
[+D+] Logger DLL loaded into process 4932 @ 0x6C4C0000
[+D+] Logging process 4932 to log file 'C:\Users\Crash Analysis - 2\AppData\Local\Temp\Low\logger_4932.xml'

Any suggestions?

**Comment by hacksysteam** [comment]
I checked with Firefox 40.0.3 there is no mozjs.dll which is used by Grinder for logging..

**Comment by hacksysteam** [comment]
@pyoor The issue has been resolved, could you please check the latest pull request and verify from your end.

**Comment by stephenfewer** [comment]
I can verify this is working for latest FF, thanks @hacksysteam for the fix!
